### ISSUE TITLE
SyntaxError: Unexpected token  in JSON... 

### ISSUE THREAD

**Issue by BlitZz96** [Jqmey/cleverbot-api#1]
When parsing the response, the code breaks because of the JSON response is malfunctioned sometimes.
I have yet to find the reason, but I think it lies on cleverbot's side.

My workaround is to catch the JSON.parse in [index.js:23](https://github.com/Jqmey/cleverbot-api/blob/49347925eb9e383307647779eb6bd93fc34ea4a9/index.js#L23)

Seems to fix the problem in a hacky way 😞

**Comment by Jqmey** [comment]
Fixed in 65df717. Thanks for reporting.

Now it returns a `CleverbotAPIError` with message `Invalid response!`.

**Comment by Jqmey** [comment]
@BlitZz96 how many times have you had such situation? I have queried the bot using this library over 1000 times and it never broke when parsing JSON.

**Comment by BlitZz96** [comment]
It happened 3 times, totally random. Just chatting with the bot until it does not answer due to the broken JSON 🍂

**Comment by Jqmey** [comment]
In what enviroment the problem occured (system, node version, etc.)?

**Comment by BlitZz96** [comment]
Windows 10, node v7.9.0, Discord bot (Discord.js)

**Comment by Jqmey** [comment]
Tried to reproduce it in the same enviroment. Error didn't occur. Must be something with your client ¯\_(ツ)_/¯.

**Comment by BlitZz96** [comment]
haven't had the problem occur after 1.sep. Maybe they did some maintenance on the bot.
I strongly do not think there is something wrong with my environment as of what the error is. But you never know 🍔 Anyways, good and clean code man! That's why I chose this instead of the other's. Keep it up!
